version: '3'

networks:
    statfive-network:


volumes:
    mariadb_data:
    video:


services:
    api:
        build: ./api
        image: acalhabi/statfive_api
        links:
            - mariadb
            - tracker-app
        depends_on:
            - mariadb
            - tracker-app
        ports:
            - 5000
        networks:
            - statfive-network
        environment:
            - PYTHONUNBUFFERED=0
            - MYSQL_DATABASE=statfive
            - MYSQL_USER=statfive_user
            - MYSQL_PASSWORD=statfive_password
            - MYSQL_HOST=mariadb
            - PROD=docker
        volumes:
            - video:/app/video
        restart: always

    mariadb:
        image: mariadb
        tty: true
        restart: always
        ports:
            - 3306
        environment:
            MYSQL_DATABASE: statfive
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: statfive_user
            MYSQL_PASSWORD: statfive_password
        networks:
            - statfive-network
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d
  
    nginx:
        image: nginx
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - /etc/letsencrypt:/etc/letsencrypt
        ports:
            - 80:80
            - 443:443
        networks:
            - statfive-network
        links:
            - web
            - api
        depends_on:
            - web
            - api

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb
        depends_on:
            - mariadb
        ports:
            - 80
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: root 
        networks:
            - statfive-network
        restart: always

    redis:
        image: redis:7.0.0
        ports:
            - 6379
        networks:
            - statfive-network
        restart: always

    tracker-app:
        build: ./tracker
        image: acalhabi/statfive_tracker
        ports:
            - 5000
        networks:
            - statfive-network
        volumes:
            - video:/app/video
        links:
            - redis
        depends_on:
            - redis
        restart: always

    tracker-worker:
        build: ./tracker
        image: acalhabi/statfive_tracker
        command: rq worker --url redis://redis:6379
        networks:
            - statfive-network
        volumes:
            - video:/app/video
        environment:
            OBJC_DISABLE_INITIALIZE_FORK_SAFETY: "YES"
        links:
            - redis
        depends_on:
            - redis
            - tracker-app
        restart: always

    web:
        build: ./web
        image: acalhabi/statfive_web
        command: npm run dev
        volumes:
            - ./web:/app
            - /app/node_modules
        ports:
            - 3000
        networks:
            - statfive-network
        depends_on:
            - mariadb
            - api
        environment:
            - API_URL=https://api.preprod.statfive.fr/api
        restart: always