apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: reverse
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.statfive.fr`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: traefik
spec:
  entryPoints: 
    - websecure
  routes:
    - kind: Rule
      match: Host(`dashboard.statfive.fr`)
      services:
        - name: web
          namespace: statfive
          port: 3000
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api
  namespace: traefik
spec:
  entryPoints: 
    - websecure
  routes:
    - kind: Rule
      match: Host(`api.statfive.fr`)
      services:
        - name: api
          namespace: statfive
          port: 5000
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tracker
  namespace: traefik
spec:
  entryPoints: 
    - websecure
  routes:
    - kind: Rule
      match: Host(`tracker.statfive.fr`)
      services:
        - name: tracker
          namespace: statfive
          port: 5000
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: phpmyadmin
  namespace: traefik
spec:
  entryPoints: 
    - websecure
  routes:
    - kind: Rule
      match: Host(`phpmyadmin.statfive.fr`)
      services:
        - name: phpmyadmin
          namespace: statfive
          port: 80
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.statfive.fr`)
      kind: Rule
      services:
        - name: prometheus-k8s
          namespace: monitoring
          port: 9090
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.statfive.fr`)
      kind: Rule
      services:
        - name: grafana
          namespace: monitoring
          port: 3000
  tls:
    certResolver: letsencrypt

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: metrics
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/metrics`)
      kind: Rule
      services:
        - name: prometheus@internal
          kind: TraefikService
