
stages:
  - test
  - setup
  - build
  - publish
  - deploy


.ssh-connect-preprod:
  image: debian:11
  variables:
    COMMAND: "echo 'You need to implement COMMAND Variable'"
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/known_hosts
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  script:
    - ssh "$PREPROD_GITUSER"@"$PREPROD_SERVER_IP" "cd $PATH_GPE_DIR; $COMMAND"


unit-test-tracker:
  stage: test
  script:
    - echo "Running unit tests... This will take about 1 seconds."
    - echo "Code coverage is 90%"

lint-tracker:
  stage: test
  script:
    - echo "Linting code... This will take about 1 seconds."
    - echo "No lint issues found."


pull-tracker-git:
  stage: setup
  extends: .ssh-connect-preprod
  variables:
    COMMAND: "cd tracker/ && git pull origin master"
  needs: [unit-test-tracker, lint-tracker]
  only:
    refs:
      - staging


build-tracker:
  stage: build
  extends: .ssh-connect-preprod
  variables:
    COMMAND: "sudo docker-compose build tracker"
  needs: [pull-tracker-git]
  only:
    refs:
      - staging


publish-tracker:
  stage: publish
  extends: .ssh-connect-preprod
  variables:
    COMMAND: "sudo docker push acalhabi/statfive_tracker"
  only:
    refs:
      - master


deploy-preprod-tracker:
  stage: deploy
  extends: .ssh-connect-preprod
  variables:
    COMMAND: "sudo docker-compose up -d"
  needs: [build-tracker]
  only:
    refs:
      - staging

deploy-prod-tracker-app:
  stage: deploy
  extends: .ssh-connect-preprod
  variables:
    COMMAND: "kubectl rollout restart deployment tracker-app -n statfive"
  needs: [publish-tracker]
  only:
    refs:
      - master

deploy-prod-tracker-worker:
  stage: deploy
  extends: .ssh-connect-preprod
  variables:
    COMMAND: "kubectl rollout restart deployment tracker-worker -n statfive"
  needs: [publish-tracker]
  only:
    refs:
      - master
